Fix MSVC build error C2397 (narrowing conversion)
signalsmith-stretch.h(407,29): error C2397: conversion from 'int' to 'size_t' requires a narrowing conversion

MSBuild version 17.13.15+18b3035f6 for .NET Framework